config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :agences

  resources :acquereurs

  resources :proprietaires

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/acquereur.rb
class Acquereur < ActiveRecord::Base
  belongs_to :user
  belongs_to :agence
end

app/controllers/acquereurs_controller.rb
class AcquereursController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_acquereur, only: [:show, :edit, :update, :destroy]

  # GET /acquereurs
  # GET /acquereurs.json
  def index
    @acquereurs = Acquereur.all
  end

  # GET /acquereurs/1
  # GET /acquereurs/1.json
  def show
  end

  # GET /acquereurs/new
  def new
    @acquereur = Acquereur.new
  end

  # GET /acquereurs/1/edit
  def edit
  end

  # POST /acquereurs
  # POST /acquereurs.json
  def create
    @acquereur = Acquereur.new(acquereur_params)
    @acquereur.user = current_user

    respond_to do |format|
      if @acquereur.save
        format.html { redirect_to @acquereur, notice: 'Acquereur was successfully created.' }
        format.json { render :show, status: :created, location: @acquereur }
      else
        format.html { render :new }
        format.json { render json: @acquereur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acquereurs/1
  # PATCH/PUT /acquereurs/1.json
  def update
    respond_to do |format|
      if @acquereur.update(acquereur_params)
        format.html { redirect_to @acquereur, notice: 'Acquereur was successfully updated.' }
        format.json { render :show, status: :ok, location: @acquereur }
      else
        format.html { render :edit }
        format.json { render json: @acquereur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acquereurs/1
  # DELETE /acquereurs/1.json
  def destroy
    @acquereur.destroy
    respond_to do |format|
      format.html { redirect_to acquereurs_url, notice: 'Acquereur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acquereur
      @acquereur = Acquereur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acquereur_params
      params.require(:acquereur).permit(:nom, :user_id, :agence_id)
    end
end

app/helpers/acquereurs_helper.rb
module AcquereursHelper
end

app/views/acquereurs/_form.html.erb
<%= form_for @acquereur, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :nom, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :nom, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  acquereurs_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/acquereurs/edit.html.erb
<%- model_class = Acquereur -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Acquereur %></h1>
</div>
<%= render :partial => 'form' %>

app/views/acquereurs/index.html.erb
<%- model_class = Acquereur -%>
<div class="page-header">
  <h1><%=t '.title', :default => Acquereur %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:nom) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @acquereurs.each do |acquereur| %>
      <tr>
        <td><%= acquereur.id %></td>
        <td><%= acquereur.nom %></td>
        <td><%=l acquereur.created_at, format: :long %></td>
        <td>
          <%= link_to acquereur_path(acquereur), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to acquereur_path(acquereur), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_acquereur_path,
            :class => 'btn btn-primary' %>

app/views/acquereurs/new.html.erb
<%- model_class = Acquereur -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Acquereur %></h1>
</div>
<%= render :partial => 'form' %>

app/views/acquereurs/show.html.erb
<%- model_class = Acquereur -%>
<div class="page-header">
  <h1><%=t '.title', :default => Acquereur %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nom) %></dt>
      <dd><pre class="prettyprint"><%= @acquereur.nom %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              acquereurs_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_acquereur_path(@acquereur), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              acquereur_path(@acquereur),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>