config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :agences

  resources :acquereurs

  resources :proprietaires

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/proprietaire.rb
class Proprietaire < ActiveRecord::Base
  belongs_to :agence
  belongs_to :user
  has_many :biens
end

app/controllers/proprietaires_controller.rb
class ProprietairesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_proprietaire, only: [:show, :edit, :update, :destroy]

  # GET /proprietaires
  # GET /proprietaires.json
  def index
    @proprietaires = Proprietaire.all
  end

  # GET /proprietaires/1
  # GET /proprietaires/1.json
  def show
  end

  # GET /proprietaires/new
  def new
    @proprietaire = Proprietaire.new
  end

  # GET /proprietaires/1/edit
  def edit
  end

  # POST /proprietaires
  # POST /proprietaires.json
  def create
    @proprietaire = Proprietaire.new(proprietaire_params)
    @proprietaire.user = current_user

    respond_to do |format|
      if @proprietaire.save
        format.html { redirect_to @proprietaire, notice: 'Proprietaire was successfully created.' }
        format.json { render :show, status: :created, location: @proprietaire }
      else
        format.html { render :new }
        format.json { render json: @proprietaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proprietaires/1
  # PATCH/PUT /proprietaires/1.json
  def update
    respond_to do |format|
      if @proprietaire.update(proprietaire_params)
        format.html { redirect_to @proprietaire, notice: 'Proprietaire was successfully updated.' }
        format.json { render :show, status: :ok, location: @proprietaire }
      else
        format.html { render :edit }
        format.json { render json: @proprietaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proprietaires/1
  # DELETE /proprietaires/1.json
  def destroy
    @proprietaire.destroy
    respond_to do |format|
      format.html { redirect_to proprietaires_url, notice: 'Proprietaire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proprietaire
      @proprietaire = Proprietaire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proprietaire_params
      params.require(:proprietaire).permit(:agence_id, :user_id, :nom)
    end
end

app/helpers/proprietaires_helper.rb
module ProprietairesHelper
end

app/views/proprietaires/_form.html.erb
<%= form_for @proprietaire, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :nom, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nom, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  proprietaires_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/proprietaires/edit.html.erb
<%- model_class = Proprietaire -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Proprietaire %></h1>
</div>
<%= render :partial => 'form' %>

app/views/proprietaires/index.html.erb
<%- model_class = Proprietaire -%>
<div class="page-header">
  <h1><%=t '.title', :default => Proprietaire %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:nom) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @proprietaires.each do |proprietaire| %>
      <tr>
        <td><%= proprietaire.id %></td>
        <td><%= proprietaire.nom %></td>
        <td><%=l proprietaire.created_at, format: :long %></td>
        <td>
          <%= link_to proprietaire_path(proprietaire), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to proprietaire_path(proprietaire), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_proprietaire_path,
            :class => 'btn btn-primary' %>

app/views/proprietaires/new.html.erb
<%- model_class = Proprietaire -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Proprietaire %></h1>
</div>
<%= render :partial => 'form' %>

app/views/proprietaires/show.html.erb
<%- model_class = Proprietaire -%>
<div class="page-header">
  <h1><%=t '.title', :default => Proprietaire %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nom) %></dt>
      <dd><pre class="prettyprint"><%= @proprietaire.nom %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              proprietaires_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_proprietaire_path(@proprietaire), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              proprietaire_path(@proprietaire),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>